### ISSUE TITLE
panic: interface conversion: interface {} is []interface {}, not string

### ISSUE THREAD

**Issue by cweems** [RJPearson94/terraform-provider-twilio#21]
## Technical Details

- MacOS
- Terraform Version: 0.14.4
- Provider Version 0.2.1

## Affected Resources

- twilio_phone_number

## Describe the bug

Running `terraform apply` using the `twilio_phone_number` resource is giving me an error:

panic: interface conversion: interface {} is []interface {}, not string

I'm fairly new to Terraform, but this seems like a Go type error from this func: https://github.com/RJPearson94/terraform-provider-twilio/blob/main/twilio/internal/services/phone_number/resource_phone_number.go#L306

Maybe this is user-error? Thanks for looking at this issue.

A clear and concise description of what the bug is. Feel free to include Terraform configuration, logs, etc.

## Steps to Reproduce

Here's what my main.tf looks like:

```
terraform {
  required_providers {
    twilio = {
      source  = "RJPearson94/twilio"
      version = ">= 0.2.1"
    }
  }
}

provider "twilio" {
  account_sid = "ACXXX"
  auth_token  = "12345"
}

resource "twilio_phone_number" "phone_number" {
  account_sid  = "ACXXX"
  phone_number = "+14153631234"

  voice {
    url = "https://twilio.com"
  }

}
```

Steps to reproduce the behaviour:

1. Step 1
Run `terraform apply`

## Expected behaviour

Purchase a Twilio number?

## Logs
```shell
panic: interface conversion: interface {} is []interface {}, not string
2021-01-21T15:40:17.141-0800 [DEBUG] plugin.terraform-provider-twilio_v0.6.1:
2021-01-21T15:40:17.141-0800 [DEBUG] plugin.terraform-provider-twilio_v0.6.1: goroutine 53 [running]:
2021-01-21T15:40:17.141-0800 [DEBUG] plugin.terraform-provider-twilio_v0.6.1: github.com/RJPearson94/terraform-provider-twilio/twilio/internal/services/phone_number.resourcePhoneNumberCreate(0x231bfc0, 0xc00060e540, 0xc00065a280, 0x1d8e6a0, 0xc0000de460, 0xc00060dde0, 0x12d3e8a, 0xc00011d420)
2021-01-21T15:40:17.141-0800 [DEBUG] plugin.terraform-provider-twilio_v0.6.1: 	github.com/RJPearson94/terraform-provider-twilio/twilio/internal/services/phone_number/resource_phone_number.go:337 +0x1bd0
2021-01-21T15:40:17.141-0800 [DEBUG] plugin.terraform-provider-twilio_v0.6.1: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xc000475ef0, 0x231bf40, 0xc00060a140, 0xc00065a280, 0x1d8e6a0, 0xc0000de460, 0x0, 0x0, 0x0)
2021-01-21T15:40:17.141-0800 [DEBUG] plugin.terraform-provider-twilio_v0.6.1: 	github.com/hashicorp/terraform-plugin-sdk/v2@v2.3.0/helper/schema/resource.go:275 +0x1ec
2021-01-21T15:40:17.141-0800 [DEBUG] plugin.terraform-provider-twilio_v0.6.1: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc000475ef0, 0x231bf40, 0xc00060a140, 0xc00062a150, 0xc00011d420, 0x1d8e6a0, 0xc0000de460, 0x0, 0x0, 0x0, ...)
2021-01-21T15:40:17.141-0800 [DEBUG] plugin.terraform-provider-twilio_v0.6.1: 	github.com/hashicorp/terraform-plugin-sdk/v2@v2.3.0/helper/schema/resource.go:386 +0x681
2021-01-21T15:40:17.141-0800 [DEBUG] plugin.terraform-provider-twilio_v0.6.1: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc000302560, 0x231bf40, 0xc00060a140, 0xc00061c0a0, 0xc00060a140, 0xc00060e100, 0x232d6c0)
2021-01-21T15:40:17.141-0800 [DEBUG] plugin.terraform-provider-twilio_v0.6.1: 	github.com/hashicorp/terraform-plugin-sdk/v2@v2.3.0/helper/schema/grpc_provider.go:951 +0x8b2
2021-01-21T15:40:17.141-0800 [DEBUG] plugin.terraform-provider-twilio_v0.6.1: github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).ApplyResourceChange(0xc000244b20, 0x231bf40, 0xc00060a140, 0xc00062a000, 0xc000244b20, 0xc000618180, 0xc000616ba0)
2021-01-21T15:40:17.141-0800 [DEBUG] plugin.terraform-provider-twilio_v0.6.1: 	github.com/hashicorp/terraform-plugin-go@v0.1.0/tfprotov5/server/server.go:331 +0xac
2021-01-21T15:40:17.141-0800 [DEBUG] plugin.terraform-provider-twilio_v0.6.1: github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0x1fe9a00, 0xc000244b20, 0x231c000, 0xc000618180, 0xc00060e120, 0x0, 0x231c000, 0xc000618180, 0xc000628500, 0x487)
2021-01-21T15:40:17.141-0800 [DEBUG] plugin.terraform-provider-twilio_v0.6.1: 	github.com/hashicorp/terraform-plugin-go@v0.1.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:380 +0x217
2021-01-21T15:40:17.142-0800 [DEBUG] plugin.terraform-provider-twilio_v0.6.1: google.golang.org/grpc.(*Server).processUnaryRPC(0xc0005d6380, 0x2329a00, 0xc00018d980, 0xc000624000, 0xc0005b2d80, 0x2c5dce0, 0x0, 0x0, 0x0)
2021-01-21T15:40:17.142-0800 [DEBUG] plugin.terraform-provider-twilio_v0.6.1: 	google.golang.org/grpc@v1.32.0/server.go:1194 +0x50a
2021-01-21T15:40:17.142-0800 [DEBUG] plugin.terraform-provider-twilio_v0.6.1: google.golang.org/grpc.(*Server).handleStream(0xc0005d6380, 0x2329a00, 0xc00018d980, 0xc000624000, 0x0)
2021-01-21T15:40:17.142-0800 [DEBUG] plugin.terraform-provider-twilio_v0.6.1: 	google.golang.org/grpc@v1.32.0/server.go:1517 +0xcfd
2021-01-21T15:40:17.142-0800 [DEBUG] plugin.terraform-provider-twilio_v0.6.1: google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc00030b0b0, 0xc0005d6380, 0x2329a00, 0xc00018d980, 0xc000624000)
2021-01-21T15:40:17.142-0800 [DEBUG] plugin.terraform-provider-twilio_v0.6.1: 	google.golang.org/grpc@v1.32.0/server.go:859 +0xa1
2021-01-21T15:40:17.142-0800 [DEBUG] plugin.terraform-provider-twilio_v0.6.1: created by google.golang.org/grpc.(*Server).serveStreams.func1
2021-01-21T15:40:17.142-0800 [DEBUG] plugin.terraform-provider-twilio_v0.6.1: 	google.golang.org/grpc@v1.32.0/server.go:857 +0x204
2021-01-21T15:40:17.144-0800 [WARN]  plugin.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"
2021-01-21T15:40:17.144-0800 [DEBUG] plugin: plugin process exited: path=.terraform/providers/registry.terraform.io/rjpearson94/twilio/0.6.1/darwin_amd64/terraform-provider-twilio_v0.6.1 pid=17726 error="exit status 2"
2021/01/21 15:40:17 [DEBUG] twilio_studio_flow.flow: apply errored, but we're indicating that via the Error pointer rather than returning it: rpc error: code = Unavailable desc = transport is closing
2021/01/21 15:40:17 [TRACE] EvalWriteState: writing current state object for twilio_studio_flow.flow
2021/01/21 15:40:17 [DEBUG] twilio_phone_number.phone_number: apply errored, but we're indicating that via the Error pointer rather than returning it: rpc error: code = Unavailable desc = transport is closing
2021/01/21 15:40:17 [TRACE] EvalMaybeTainted: twilio_phone_number.phone_number encountered an error during creation, so it is now marked as tainted
2021/01/21 15:40:17 [TRACE] EvalWriteState: removing state object for twilio_phone_number.phone_number
2021/01/21 15:40:17 [TRACE] EvalApplyProvisioners: twilio_phone_number.phone_number has no state, so skipping provisioners
2021/01/21 15:40:17 [TRACE] EvalMaybeTainted: twilio_phone_number.phone_number encountered an error during creation, so it is now marked as tainted
2021/01/21 15:40:17 [TRACE] EvalWriteState: removing state object for twilio_phone_number.phone_number
2021/01/21 15:40:17 [TRACE] vertex "twilio_phone_number.phone_number": visit complete
2021/01/21 15:40:17 [TRACE] vertex "twilio_studio_flow.flow (destroy)": visit complete
2021/01/21 15:40:17 [TRACE] dag/walk: upstream of "twilio_taskrouter_workflow.did_workflow (destroy)" errored, so skipping
2021/01/21 15:40:17 [TRACE] dag/walk: upstream of "meta.count-boundary (EachMode fixup)" errored, so skipping
2021/01/21 15:40:17 [TRACE] dag/walk: upstream of "provider[\"registry.terraform.io/rjpearson94/twilio\"] (close)" errored, so skipping
2021/01/21 15:40:17 [TRACE] dag/walk: upstream of "root" errored, so skipping
2021/01/21 15:40:17 [TRACE] statemgr.Filesystem: creating backup snapshot at terraform.tfstate.backup
2021/01/21 15:40:17 [TRACE] statemgr.Filesystem: state has changed since last snapshot, so incrementing serial to 7
2021/01/21 15:40:17 [TRACE] statemgr.Filesystem: writing snapshot at terraform.tfstate
2021/01/21 15:40:17 [TRACE] statemgr.Filesystem: removing lock metadata file .terraform.tfstate.lock.info
2021/01/21 15:40:17 [TRACE] statemgr.Filesystem: unlocking terraform.tfstate using fcntl flock
2021-01-21T15:40:17.177-0800 [DEBUG] plugin: plugin exited
```

**Comment by RJPearson94** [comment]
Hi @cweems,

Thanks for raising the issue. I can confirm this is a bug in the terraform provider. Apologies about this. I will hopefully have a fix shortly

**Comment by RJPearson94** [comment]
The change is now in the main branch. I will cut v0.6.2 shortly

**Comment by RJPearson94** [comment]
V0.6.2 has been released and pushed to the Terraform Registry.

You will need to use provider version v0.6.2 or above to receive the fix. 

Please update your provider config to the following:

```
terraform {
  required_providers {
    twilio = {
      source  = "RJPearson94/twilio"
      version = ">= 0.6.2"
    }
  }
}
```

Thanks for using the provider and if any further questions or issue arise then feel free to reach out

**Comment by cweems** [comment]
@RJPearson94 thank you for the quick fix! Just confirming that this now works for me.
